apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: eqh-spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: eqh-spring-boot-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: eqh-spring-boot-k8s
    spec:
      containers:
        - name: eqh-spring-boot-k8s
          image: githubpocrg.azurecr.io/myimage:4ccfb81d80830f02072389be515ba3f14f9394d7 
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
# The port that the container is running on in the cluster
